-- Apply after 20260910_team_onboarding.sql, using the same schema variable.
BEGIN;
SET LOCAL search_path TO :"schema", public;
INSERT INTO system_email_template (context, iso_639_1, subject, template) VALUES ('team-invite-accepted', 'de', $subject${{member_name}} ist dem Team von {{organization_name}} beigetreten$subject$, $html$<!doctype html><html lang="de"><body><p>Hallo {{display_name}},</p><p>{{member_name}} hat deine Einladung angenommen und ist jetzt Mitglied im Team von {{organization_name}}.</p><p>Das neue Teammitglied startet ohne zusätzliche Berechtigungen. Lege jetzt fest, welche Bereiche es verwalten darf.</p><p><a href="{{action_link}}">Berechtigungen festlegen</a></p><p>Kulturbytes</p></body></html>$html$) ON CONFLICT (context, iso_639_1) DO NOTHING;
INSERT INTO system_email_template (context, iso_639_1, subject, template) VALUES ('team-joined', 'de', $subject$Du bist jetzt Mitglied im Team von {{organization_name}}$subject$, $html$<!doctype html><html lang="de"><body><p>Hallo {{display_name}},</p><p>Du hast die Einladung erfolgreich angenommen und bist jetzt Mitglied im Team von {{organization_name}}.</p><p>Welche Bereiche du bearbeiten kannst, hängt von den Berechtigungen ab, die dir die Organisation zuweist.</p><p><a href="{{action_link}}">Organisation öffnen</a></p><p>Kulturbytes</p></body></html>$html$) ON CONFLICT (context, iso_639_1) DO NOTHING;
INSERT INTO system_email_template (context, iso_639_1, subject, template) VALUES ('team-invite-accepted', 'en', $subject${{member_name}} has joined the team at {{organization_name}}$subject$, $html$<!doctype html><html lang="en"><body><p>Hello {{display_name}},</p><p>{{member_name}} accepted your invitation and is now a member of the team at {{organization_name}}.</p><p>The new member starts without additional permissions. You can now choose which areas they may manage.</p><p><a href="{{action_link}}">Set permissions</a></p><p>Kulturbytes</p></body></html>$html$) ON CONFLICT (context, iso_639_1) DO NOTHING;
INSERT INTO system_email_template (context, iso_639_1, subject, template) VALUES ('team-joined', 'en', $subject$You are now a team member at {{organization_name}}$subject$, $html$<!doctype html><html lang="en"><body><p>Hello {{display_name}},</p><p>You accepted the invitation and are now a member of the team at {{organization_name}}.</p><p>The areas you can edit depend on the permissions assigned to you by the organization.</p><p><a href="{{action_link}}">Open organization</a></p><p>Kulturbytes</p></body></html>$html$) ON CONFLICT (context, iso_639_1) DO NOTHING;
INSERT INTO system_email_template (context, iso_639_1, subject, template) VALUES ('team-invite-accepted', 'da', $subject${{member_name}} er blevet en del af teamet hos {{organization_name}}$subject$, $html$<!doctype html><html lang="da"><body><p>Hej {{display_name}},</p><p>{{member_name}} har accepteret din invitation og er nu medlem af teamet hos {{organization_name}}.</p><p>Det nye medlem starter uden yderligere rettigheder. Du kan nu vælge, hvilke områder medlemmet må administrere.</p><p><a href="{{action_link}}">Indstil rettigheder</a></p><p>Kulturbytes</p></body></html>$html$) ON CONFLICT (context, iso_639_1) DO NOTHING;
INSERT INTO system_email_template (context, iso_639_1, subject, template) VALUES ('team-joined', 'da', $subject$Du er nu medlem af teamet hos {{organization_name}}$subject$, $html$<!doctype html><html lang="da"><body><p>Hej {{display_name}},</p><p>Du har accepteret invitationen og er nu medlem af teamet hos {{organization_name}}.</p><p>De områder, du kan redigere, afhænger af de rettigheder, organisationen tildeler dig.</p><p><a href="{{action_link}}">Åbn organisation</a></p><p>Kulturbytes</p></body></html>$html$) ON CONFLICT (context, iso_639_1) DO NOTHING;
COMMIT;
