e.id AS id,
event_date_id,
e.title AS title,
e.subtitle AS subtitle,
o.id AS organizer_id,
o.name AS organizer_name,
v.id AS venue_id,
v.name AS venue_name,
v.street AS venue_street,
v.house_number AS venue_house_number,
v.postal_code AS venue_postal_code,
v.city AS venue_city,
v.country_code AS venue_country,
v.state_code AS venue_state,
COALESCE(s.id, es.id) AS space_id,
COALESCE(s.name, es.name) AS space_name,
TO_CHAR(ed.start, 'YYYY-MM-DD') AS start_date,
TO_CHAR(ed.start, 'HH24:MI') AS start_time,
TO_CHAR(ed.end, 'YYYY-MM-DD') AS end_date,
TO_CHAR(ed.end, 'HH24:MI') AS end_time,
TO_CHAR(ed.entry_time, 'HH24:MI') AS entry_time,
et_data.event_types,
ST_X(v.wkb_geometry) AS venue_lon,
ST_Y(v.wkb_geometry) AS venue_lat
