e.id AS id,
event_date_id,
e.title AS title,
e.subtitle AS subtitle,
o.id AS organizer_id,
o.name AS organizer_name,
v.id AS venue_id,
v.name AS venue_name,
v.street AS venue_street,
v.house_number AS venue_house_number,
v.postal_code AS venue_postal_code,
v.city AS venue_city,
v.country_code AS venue_country,
v.state_code AS venue_state,
COALESCE(s.id, es.id) AS space_id,
COALESCE(s.name, es.name) AS space_name,
TO_CHAR(ed.start_date, 'YYYY-MM-DD') AS start_date,
TO_CHAR(ed.start_time, 'HH24:MI') AS start_time,
TO_CHAR(ed.end_date, 'YYYY-MM-DD') AS end_date,
TO_CHAR(ed.end_time, 'HH24:MI') AS end_time,
TO_CHAR(ed.entry_time, 'HH24:MI') AS entry_time,
et_data.event_types,
img_data.id AS image_id,

e.languages,
e.min_age,
e.max_age,
ed.duration AS duration,

e.description AS description,
e.teaser_text AS teaser_text,
e.participation_info AS participation_info,
e.meeting_point AS meeting_point,
e.source_url,
e.tags,
COALESCE(s.total_capacity, es.total_capacity) AS space_total_capacity,
COALESCE(s.seating_capacity, es.seating_capacity) AS space_seating_capacity,
COALESCE(s.building_level, es.building_level) AS space_building_level,
COALESCE(s.website_url, es.website_url) AS space_url,
ed.visitor_info_flags AS visitor_info_flags,
vis_flags.visitor_info_flag_names AS visitor_info_flag_names,
(img_data.has_main_image) AS has_main_image,
img_data.focus_x AS image_focus_x,
img_data.focus_y AS image_focus_y