e.id AS id,
event_date_id,
e.title AS title,
e.subtitle AS subtitle,
o.id AS organizer_id,
o.name AS organizer_name,
COALESCE(v_ed.id, v_ev.id) AS venue_id,
COALESCE(v_ed.name, v_ev.name) AS venue_name,
COALESCE(v_ed.street, v_ev.street) AS venue_street,
COALESCE(v_ed.house_number, v_ev.house_number) AS venue_house_number,
COALESCE(v_ed.postal_code, v_ev.postal_code) AS venue_postal_code,
COALESCE(v_ed.city, v_ev.city) AS venue_city,
COALESCE(v_ed.country_code, v_ev.country_code) AS venue_country_code,
COALESCE(v_ed.state_code, v_ev.state_code) AS venue_state_code,
COALESCE(s.id, es.id) AS space_id,
COALESCE(s.name, es.name) AS space_name,
TO_CHAR(ed.start_date, 'YYYY-MM-DD') AS start_date,
TO_CHAR(ed.start_time, 'HH24:MI') AS start_time,
TO_CHAR(ed.end_date, 'YYYY-MM-DD') AS end_date,
TO_CHAR(ed.end_time, 'HH24:MI') AS end_time,
TO_CHAR(ed.entry_time, 'HH24:MI') AS entry_time,
et_data.event_types,
image_data.id AS image_id,
image_data.focus_x AS image_focus_x,
image_data.focus_y AS image_focus_y,

e.languages,
e.min_age,
e.max_age,
ed.duration AS duration