e.id AS id,
event_date_id,
e.title AS title,
e.subtitle AS subtitle,
o.id AS organization_id,
o.name AS organization_name,
vd.venue_id,
vd.venue_name,
vd.venue_street,
vd.venue_house_number,
vd.venue_postal_code,
vd.venue_city,
vd.venue_country_code,
vd.venue_state_code,
vd.venue_lon,
vd.venue_lat,
vd.venue_wkb_pos,
COALESCE(s.id, es.id) AS space_id,
COALESCE(s.name, es.name) AS space_name,
TO_CHAR(ed.start_date, 'YYYY-MM-DD') AS start_date,
TO_CHAR(ed.start_time, 'HH24:MI') AS start_time,
TO_CHAR(ed.end_date, 'YYYY-MM-DD') AS end_date,
TO_CHAR(ed.end_time, 'HH24:MI') AS end_time,
TO_CHAR(ed.entry_time, 'HH24:MI') AS entry_time,
et_data.event_types,
image_data.id AS image_id,
image_data.focus_x AS image_focus_x,
image_data.focus_y AS image_focus_y

