INSERT INTO countries (code, name, iso_639_1) VALUES
('ABW', 'Aruba', 'en'),
('ABW', 'Aruba', 'de'),
('ABW', 'Aruba', 'da'),
('AFG', 'Afghanistan', 'en'),
('AFG', 'Afghanistan', 'de'),
('AFG', 'Afghanistan', 'da'),
('AGO', 'Angola', 'en'),
('AGO', 'Angola', 'de'),
('AGO', 'Angola', 'da'),
('AIA', 'Anguilla', 'en'),
('AIA', 'Anguilla', 'de'),
('AIA', 'Anguilla', 'da'),
('ALA', 'Åland Islands', 'en'),
('ALA', 'Ålandinseln', 'de'),
('ALA', 'Åland', 'da'),
('ALB', 'Albania', 'en'),
('ALB', 'Albanien', 'de'),
('ALB', 'Albanien', 'da'),
('AND', 'Andorra', 'en'),
('AND', 'Andorra', 'de'),
('AND', 'Andorra', 'da'),
('ARE', 'United Arab Emirates', 'en'),
('ARE', 'Vereinigte Arabische Emirate', 'de'),
('ARE', 'De Forenede Arabiske Emirater', 'da'),
('ARG', 'Argentina', 'en'),
('ARG', 'Argentinien', 'de'),
('ARG', 'Argentina', 'da'),
('ARM', 'Armenia', 'en'),
('ARM', 'Armenien', 'de'),
('ARM', 'Armenien', 'da'),
('ASM', 'American Samoa', 'en'),
('ASM', 'Amerikanisch-Samoa', 'de'),
('ASM', 'Amerikansk Samoa', 'da'),
('ATA', 'Antarctica', 'en'),
('ATA', 'Antarktis', 'de'),
('ATA', 'Antarktis', 'da'),
('ATF', 'French Southern Territories', 'en'),
('ATF', 'Französische Süd- und Antarktisgebiete', 'de'),
('ATF', 'De Franske Besiddelser i Det Sydlige Indiske Ocean og Antarktis', 'da'),
('ATG', 'Antigua and Barbuda', 'en'),
('ATG', 'Antigua und Barbuda', 'de'),
('ATG', 'Antigua og Barbuda', 'da'),
('AUS', 'Australia', 'en'),
('AUS', 'Australien', 'de'),
('AUS', 'Australien', 'da'),
('AUT', 'Austria', 'en'),
('AUT', 'Österreich', 'de'),
('AUT', 'Østrig', 'da'),
('AZE', 'Azerbaijan', 'en'),
('AZE', 'Aserbaidschan', 'de'),
('AZE', 'Aserbajdsjan', 'da'),
('BDI', 'Burundi', 'en'),
('BDI', 'Burundi', 'de'),
('BDI', 'Burundi', 'da'),
('BEL', 'Belgium', 'en'),
('BEL', 'Belgien', 'de'),
('BEL', 'Belgien', 'da'),
('BEN', 'Benin', 'en'),
('BEN', 'Benin', 'de'),
('BEN', 'Benin', 'da'),
('BES', 'Bonaire, Sint Eustatius and Saba', 'en'),
('BES', 'Karibische Niederlande', 'de'),
('BES', 'De tidligere Nederlandske Antiller', 'da'),
('BFA', 'Burkina Faso', 'en'),
('BFA', 'Burkina Faso', 'de'),
('BFA', 'Burkina Faso', 'da'),
('BGD', 'Bangladesh', 'en'),
('BGD', 'Bangladesch', 'de'),
('BGD', 'Bangladesh', 'da'),
('BGR', 'Bulgaria', 'en'),
('BGR', 'Bulgarien', 'de'),
('BGR', 'Bulgarien', 'da'),
('BHR', 'Bahrain', 'en'),
('BHR', 'Bahrain', 'de'),
('BHR', 'Bahrain', 'da'),
('BHS', 'Bahamas', 'en'),
('BHS', 'Bahamas', 'de'),
('BHS', 'Bahamas', 'da'),
('BIH', 'Bosnia and Herzegovina', 'en'),
('BIH', 'Bosnien und Herzegowina', 'de'),
('BIH', 'Bosnien-Hercegovina', 'da'),
('BLM', 'Saint Barthélemy', 'en'),
('BLM', 'St. Barthélemy', 'de'),
('BLM', 'Saint Barthélemy', 'da'),
('BLR', 'Belarus', 'en'),
('BLR', 'Belarus', 'de'),
('BLR', 'Belarus', 'da'),
('BLZ', 'Belize', 'en'),
('BLZ', 'Belize', 'de'),
('BLZ', 'Belize', 'da'),
('BMU', 'Bermuda', 'en'),
('BMU', 'Bermuda', 'de'),
('BMU', 'Bermuda', 'da'),
('BOL', 'Bolivia, Plurinational State of', 'en'),
('BOL', 'Bolivien', 'de'),
('BOL', 'Bolivia', 'da'),
('BRA', 'Brazil', 'en'),
('BRA', 'Brasilien', 'de'),
('BRA', 'Brasilien', 'da'),
('BRB', 'Barbados', 'en'),
('BRB', 'Barbados', 'de'),
('BRB', 'Barbados', 'da'),
('BRN', 'Brunei Darussalam', 'en'),
('BRN', 'Brunei Darussalam', 'de'),
('BRN', 'Brunei', 'da'),
('BTN', 'Bhutan', 'en'),
('BTN', 'Bhutan', 'de'),
('BTN', 'Bhutan', 'da'),
('BVT', 'Bouvet Island', 'en'),
('BVT', 'Bouvetinsel', 'de'),
('BVT', 'Bouvetøen', 'da'),
('BWA', 'Botswana', 'en'),
('BWA', 'Botsuana', 'de'),
('BWA', 'Botswana', 'da'),
('CAF', 'Central African Republic', 'en'),
('CAF', 'Zentralafrikanische Republik', 'de'),
('CAF', 'Den Centralafrikanske Republik', 'da'),
('CAN', 'Canada', 'en'),
('CAN', 'Kanada', 'de'),
('CAN', 'Canada', 'da'),
('CCK', 'Cocos (Keeling) Islands', 'en'),
('CCK', 'Kokosinseln', 'de'),
('CCK', 'Cocosøerne', 'da'),
('CHE', 'Switzerland', 'en'),
('CHE', 'Schweiz', 'de'),
('CHE', 'Schweiz', 'da'),
('CHL', 'Chile', 'en'),
('CHL', 'Chile', 'de'),
('CHL', 'Chile', 'da'),
('CHN', 'China', 'en'),
('CHN', 'China', 'de'),
('CHN', 'Kina', 'da'),
('CIV', 'Côte d''Ivoire', 'en'),
('CIV', 'Côte d’Ivoire', 'de'),
('CIV', 'Elfenbenskysten', 'da'),
('CMR', 'Cameroon', 'en'),
('CMR', 'Kamerun', 'de'),
('CMR', 'Cameroun', 'da'),
('COD', 'Congo, The Democratic Republic of the', 'en'),
('COD', 'Kongo-Kinshasa', 'de'),
('COD', 'Congo-Kinshasa', 'da'),
('COG', 'Congo', 'en'),
('COG', 'Kongo-Brazzaville', 'de'),
('COG', 'Congo-Brazzaville', 'da'),
('COK', 'Cook Islands', 'en'),
('COK', 'Cookinseln', 'de'),
('COK', 'Cookøerne', 'da'),
('COL', 'Colombia', 'en'),
('COL', 'Kolumbien', 'de'),
('COL', 'Colombia', 'da'),
('COM', 'Comoros', 'en'),
('COM', 'Komoren', 'de'),
('COM', 'Comorerne', 'da'),
('CPV', 'Cabo Verde', 'en'),
('CPV', 'Cabo Verde', 'de'),
('CPV', 'Kap Verde', 'da'),
('CRI', 'Costa Rica', 'en'),
('CRI', 'Costa Rica', 'de'),
('CRI', 'Costa Rica', 'da'),
('CUB', 'Cuba', 'en'),
('CUB', 'Kuba', 'de'),
('CUB', 'Cuba', 'da'),
('CUW', 'Curaçao', 'en'),
('CUW', 'Curaçao', 'de'),
('CUW', 'Curaçao', 'da'),
('CXR', 'Christmas Island', 'en'),
('CXR', 'Weihnachtsinsel', 'de'),
('CXR', 'Juleøen', 'da'),
('CYM', 'Cayman Islands', 'en'),
('CYM', 'Kaimaninseln', 'de'),
('CYM', 'Caymanøerne', 'da'),
('CYP', 'Cyprus', 'en'),
('CYP', 'Zypern', 'de'),
('CYP', 'Cypern', 'da'),
('CZE', 'Czechia', 'en'),
('CZE', 'Tschechien', 'de'),
('CZE', 'Tjekkiet', 'da'),
('DEU', 'Germany', 'en'),
('DEU', 'Deutschland', 'de'),
('DEU', 'Tyskland', 'da'),
('DJI', 'Djibouti', 'en'),
('DJI', 'Dschibuti', 'de'),
('DJI', 'Djibouti', 'da'),
('DMA', 'Dominica', 'en'),
('DMA', 'Dominica', 'de'),
('DMA', 'Dominica', 'da'),
('DNK', 'Denmark', 'en'),
('DNK', 'Dänemark', 'de'),
('DNK', 'Danmark', 'da'),
('DOM', 'Dominican Republic', 'en'),
('DOM', 'Dominikanische Republik', 'de'),
('DOM', 'Den Dominikanske Republik', 'da'),
('DZA', 'Algeria', 'en'),
('DZA', 'Algerien', 'de'),
('DZA', 'Algeriet', 'da'),
('ECU', 'Ecuador', 'en'),
('ECU', 'Ecuador', 'de'),
('ECU', 'Ecuador', 'da'),
('EGY', 'Egypt', 'en'),
('EGY', 'Ägypten', 'de'),
('EGY', 'Egypten', 'da'),
('ERI', 'Eritrea', 'en'),
('ERI', 'Eritrea', 'de'),
('ERI', 'Eritrea', 'da'),
('ESH', 'Western Sahara', 'en'),
('ESH', 'Westsahara', 'de'),
('ESH', 'Vestsahara', 'da'),
('ESP', 'Spain', 'en'),
('ESP', 'Spanien', 'de'),
('ESP', 'Spanien', 'da'),
('EST', 'Estonia', 'en'),
('EST', 'Estland', 'de'),
('EST', 'Estland', 'da'),
('ETH', 'Ethiopia', 'en'),
('ETH', 'Äthiopien', 'de'),
('ETH', 'Etiopien', 'da'),
('FIN', 'Finland', 'en'),
('FIN', 'Finnland', 'de'),
('FIN', 'Finland', 'da'),
('FJI', 'Fiji', 'en'),
('FJI', 'Fidschi', 'de'),
('FJI', 'Fiji', 'da'),
('FLK', 'Falkland Islands (Malvinas)', 'en'),
('FLK', 'Falklandinseln', 'de'),
('FLK', 'Falklandsøerne', 'da'),
('FRA', 'France', 'en'),
('FRA', 'Frankreich', 'de'),
('FRA', 'Frankrig', 'da'),
('FRO', 'Faroe Islands', 'en'),
('FRO', 'Färöer', 'de'),
('FRO', 'Færøerne', 'da'),
('FSM', 'Micronesia, Federated States of', 'en'),
('FSM', 'Mikronesien', 'de'),
('FSM', 'Mikronesien', 'da'),
('GAB', 'Gabon', 'en'),
('GAB', 'Gabun', 'de'),
('GAB', 'Gabon', 'da'),
('GBR', 'United Kingdom', 'en'),
('GBR', 'Vereinigtes Königreich', 'de'),
('GBR', 'Storbritannien', 'da'),
('GEO', 'Georgia', 'en'),
('GEO', 'Georgien', 'de'),
('GEO', 'Georgien', 'da'),
('GGY', 'Guernsey', 'en'),
('GGY', 'Guernsey', 'de'),
('GGY', 'Guernsey', 'da'),
('GHA', 'Ghana', 'en'),
('GHA', 'Ghana', 'de'),
('GHA', 'Ghana', 'da'),
('GIB', 'Gibraltar', 'en'),
('GIB', 'Gibraltar', 'de'),
('GIB', 'Gibraltar', 'da'),
('GIN', 'Guinea', 'en'),
('GIN', 'Guinea', 'de'),
('GIN', 'Guinea', 'da'),
('GLP', 'Guadeloupe', 'en'),
('GLP', 'Guadeloupe', 'de'),
('GLP', 'Guadeloupe', 'da'),
('GMB', 'Gambia', 'en'),
('GMB', 'Gambia', 'de'),
('GMB', 'Gambia', 'da'),
('GNB', 'Guinea-Bissau', 'en'),
('GNB', 'Guinea-Bissau', 'de'),
('GNB', 'Guinea-Bissau', 'da'),
('GNQ', 'Equatorial Guinea', 'en'),
('GNQ', 'Äquatorialguinea', 'de'),
('GNQ', 'Ækvatorialguinea', 'da'),
('GRC', 'Greece', 'en'),
('GRC', 'Griechenland', 'de'),
('GRC', 'Grækenland', 'da'),
('GRD', 'Grenada', 'en'),
('GRD', 'Grenada', 'de'),
('GRD', 'Grenada', 'da'),
('GRL', 'Greenland', 'en'),
('GRL', 'Grönland', 'de'),
('GRL', 'Grønland', 'da'),
('GTM', 'Guatemala', 'en'),
('GTM', 'Guatemala', 'de'),
('GTM', 'Guatemala', 'da'),
('GUF', 'French Guiana', 'en'),
('GUF', 'Französisch-Guayana', 'de'),
('GUF', 'Fransk Guyana', 'da'),
('GUM', 'Guam', 'en'),
('GUM', 'Guam', 'de'),
('GUM', 'Guam', 'da'),
('GUY', 'Guyana', 'en'),
('GUY', 'Guyana', 'de'),
('GUY', 'Guyana', 'da'),
('HKG', 'Hong Kong', 'en'),
('HKG', 'Sonderverwaltungsregion Hongkong', 'de'),
('HKG', 'SAR Hongkong', 'da'),
('HMD', 'Heard Island and McDonald Islands', 'en'),
('HMD', 'Heard und McDonaldinseln', 'de'),
('HMD', 'Heard Island og McDonald Islands', 'da'),
('HND', 'Honduras', 'en'),
('HND', 'Honduras', 'de'),
('HND', 'Honduras', 'da'),
('HRV', 'Croatia', 'en'),
('HRV', 'Kroatien', 'de'),
('HRV', 'Kroatien', 'da'),
('HTI', 'Haiti', 'en'),
('HTI', 'Haiti', 'de'),
('HTI', 'Haiti', 'da'),
('HUN', 'Hungary', 'en'),
('HUN', 'Ungarn', 'de'),
('HUN', 'Ungarn', 'da'),
('IDN', 'Indonesia', 'en'),
('IDN', 'Indonesien', 'de'),
('IDN', 'Indonesien', 'da'),
('IMN', 'Isle of Man', 'en'),
('IMN', 'Isle of Man', 'de'),
('IMN', 'Isle of Man', 'da'),
('IND', 'India', 'en'),
('IND', 'Indien', 'de'),
('IND', 'Indien', 'da'),
('IOT', 'British Indian Ocean Territory', 'en'),
('IOT', 'Britisches Territorium im Indischen Ozean', 'de'),
('IOT', 'Det Britiske Territorium i Det Indiske Ocean', 'da'),
('IRL', 'Ireland', 'en'),
('IRL', 'Irland', 'de'),
('IRL', 'Irland', 'da'),
('IRN', 'Iran, Islamic Republic of', 'en'),
('IRN', 'Iran', 'de'),
('IRN', 'Iran', 'da'),
('IRQ', 'Iraq', 'en'),
('IRQ', 'Irak', 'de'),
('IRQ', 'Irak', 'da'),
('ISL', 'Iceland', 'en'),
('ISL', 'Island', 'de'),
('ISL', 'Island', 'da'),
('ISR', 'Israel', 'en'),
('ISR', 'Israel', 'de'),
('ISR', 'Israel', 'da'),
('ITA', 'Italy', 'en'),
('ITA', 'Italien', 'de'),
('ITA', 'Italien', 'da'),
('JAM', 'Jamaica', 'en'),
('JAM', 'Jamaika', 'de'),
('JAM', 'Jamaica', 'da'),
('JEY', 'Jersey', 'en'),
('JEY', 'Jersey', 'de'),
('JEY', 'Jersey', 'da'),
('JOR', 'Jordan', 'en'),
('JOR', 'Jordanien', 'de'),
('JOR', 'Jordan', 'da'),
('JPN', 'Japan', 'en'),
('JPN', 'Japan', 'de'),
('JPN', 'Japan', 'da'),
('KAZ', 'Kazakhstan', 'en'),
('KAZ', 'Kasachstan', 'de'),
('KAZ', 'Kasakhstan', 'da'),
('KEN', 'Kenya', 'en'),
('KEN', 'Kenia', 'de'),
('KEN', 'Kenya', 'da'),
('KGZ', 'Kyrgyzstan', 'en'),
('KGZ', 'Kirgisistan', 'de'),
('KGZ', 'Kirgisistan', 'da'),
('KHM', 'Cambodia', 'en'),
('KHM', 'Kambodscha', 'de'),
('KHM', 'Cambodja', 'da'),
('KIR', 'Kiribati', 'en'),
('KIR', 'Kiribati', 'de'),
('KIR', 'Kiribati', 'da'),
('KNA', 'Saint Kitts and Nevis', 'en'),
('KNA', 'St. Kitts und Nevis', 'de'),
('KNA', 'Saint Kitts og Nevis', 'da'),
('KOR', 'Korea, Republic of', 'en'),
('KOR', 'Südkorea', 'de'),
('KOR', 'Sydkorea', 'da'),
('KWT', 'Kuwait', 'en'),
('KWT', 'Kuwait', 'de'),
('KWT', 'Kuwait', 'da'),
('LAO', 'Lao People''s Democratic Republic', 'en'),
('LAO', 'Laos', 'de'),
('LAO', 'Laos', 'da'),
('LBN', 'Lebanon', 'en'),
('LBN', 'Libanon', 'de'),
('LBN', 'Libanon', 'da'),
('LBR', 'Liberia', 'en'),
('LBR', 'Liberia', 'de'),
('LBR', 'Liberia', 'da'),
('LBY', 'Libya', 'en'),
('LBY', 'Libyen', 'de'),
('LBY', 'Libyen', 'da'),
('LCA', 'Saint Lucia', 'en'),
('LCA', 'St. Lucia', 'de'),
('LCA', 'Saint Lucia', 'da'),
('LIE', 'Liechtenstein', 'en'),
('LIE', 'Liechtenstein', 'de'),
('LIE', 'Liechtenstein', 'da'),
('LKA', 'Sri Lanka', 'en'),
('LKA', 'Sri Lanka', 'de'),
('LKA', 'Sri Lanka', 'da'),
('LSO', 'Lesotho', 'en'),
('LSO', 'Lesotho', 'de'),
('LSO', 'Lesotho', 'da'),
('LTU', 'Lithuania', 'en'),
('LTU', 'Litauen', 'de'),
('LTU', 'Litauen', 'da'),
('LUX', 'Luxembourg', 'en'),
('LUX', 'Luxemburg', 'de'),
('LUX', 'Luxembourg', 'da'),
('LVA', 'Latvia', 'en'),
('LVA', 'Lettland', 'de'),
('LVA', 'Letland', 'da'),
('MAC', 'Macao', 'en'),
('MAC', 'Sonderverwaltungsregion Macau', 'de'),
('MAC', 'SAR Macao', 'da'),
('MAF', 'Saint Martin (French part)', 'en'),
('MAF', 'St. Martin', 'de'),
('MAF', 'Saint Martin', 'da'),
('MAR', 'Morocco', 'en'),
('MAR', 'Marokko', 'de'),
('MAR', 'Marokko', 'da'),
('MCO', 'Monaco', 'en'),
('MCO', 'Monaco', 'de'),
('MCO', 'Monaco', 'da'),
('MDA', 'Moldova, Republic of', 'en'),
('MDA', 'Republik Moldau', 'de'),
('MDA', 'Moldova', 'da'),
('MDG', 'Madagascar', 'en'),
('MDG', 'Madagaskar', 'de'),
('MDG', 'Madagaskar', 'da'),
('MDV', 'Maldives', 'en'),
('MDV', 'Malediven', 'de'),
('MDV', 'Maldiverne', 'da'),
('MEX', 'Mexico', 'en'),
('MEX', 'Mexiko', 'de'),
('MEX', 'Mexico', 'da'),
('MHL', 'Marshall Islands', 'en'),
('MHL', 'Marshallinseln', 'de'),
('MHL', 'Marshalløerne', 'da'),
('MKD', 'North Macedonia', 'en'),
('MKD', 'Nordmazedonien', 'de'),
('MKD', 'Nordmakedonien', 'da'),
('MLI', 'Mali', 'en'),
('MLI', 'Mali', 'de'),
('MLI', 'Mali', 'da'),
('MLT', 'Malta', 'en'),
('MLT', 'Malta', 'de'),
('MLT', 'Malta', 'da'),
('MMR', 'Myanmar', 'en'),
('MMR', 'Myanmar', 'de'),
('MMR', 'Myanmar (Burma)', 'da'),
('MNE', 'Montenegro', 'en'),
('MNE', 'Montenegro', 'de'),
('MNE', 'Montenegro', 'da'),
('MNG', 'Mongolia', 'en'),
('MNG', 'Mongolei', 'de'),
('MNG', 'Mongoliet', 'da'),
('MNP', 'Northern Mariana Islands', 'en'),
('MNP', 'Nördliche Marianen', 'de'),
('MNP', 'Nordmarianerne', 'da'),
('MOZ', 'Mozambique', 'en'),
('MOZ', 'Mosambik', 'de'),
('MOZ', 'Mozambique', 'da'),
('MRT', 'Mauritania', 'en'),
('MRT', 'Mauretanien', 'de'),
('MRT', 'Mauretanien', 'da'),
('MSR', 'Montserrat', 'en'),
('MSR', 'Montserrat', 'de'),
('MSR', 'Montserrat', 'da'),
('MTQ', 'Martinique', 'en'),
('MTQ', 'Martinique', 'de'),
('MTQ', 'Martinique', 'da'),
('MUS', 'Mauritius', 'en'),
('MUS', 'Mauritius', 'de'),
('MUS', 'Mauritius', 'da'),
('MWI', 'Malawi', 'en'),
('MWI', 'Malawi', 'de'),
('MWI', 'Malawi', 'da'),
('MYS', 'Malaysia', 'en'),
('MYS', 'Malaysia', 'de'),
('MYS', 'Malaysia', 'da'),
('MYT', 'Mayotte', 'en'),
('MYT', 'Mayotte', 'de'),
('MYT', 'Mayotte', 'da'),
('NAM', 'Namibia', 'en'),
('NAM', 'Namibia', 'de'),
('NAM', 'Namibia', 'da'),
('NCL', 'New Caledonia', 'en'),
('NCL', 'Neukaledonien', 'de'),
('NCL', 'Ny Kaledonien', 'da'),
('NER', 'Niger', 'en'),
('NER', 'Niger', 'de'),
('NER', 'Niger', 'da'),
('NFK', 'Norfolk Island', 'en'),
('NFK', 'Norfolkinsel', 'de'),
('NFK', 'Norfolk Island', 'da'),
('NGA', 'Nigeria', 'en'),
('NGA', 'Nigeria', 'de'),
('NGA', 'Nigeria', 'da'),
('NIC', 'Nicaragua', 'en'),
('NIC', 'Nicaragua', 'de'),
('NIC', 'Nicaragua', 'da'),
('NIU', 'Niue', 'en'),
('NIU', 'Niue', 'de'),
('NIU', 'Niue', 'da'),
('NLD', 'Netherlands', 'en'),
('NLD', 'Niederlande', 'de'),
('NLD', 'Nederlandene', 'da'),
('NOR', 'Norway', 'en'),
('NOR', 'Norwegen', 'de'),
('NOR', 'Norge', 'da'),
('NPL', 'Nepal', 'en'),
('NPL', 'Nepal', 'de'),
('NPL', 'Nepal', 'da'),
('NRU', 'Nauru', 'en'),
('NRU', 'Nauru', 'de'),
('NRU', 'Nauru', 'da'),
('NZL', 'New Zealand', 'en'),
('NZL', 'Neuseeland', 'de'),
('NZL', 'New Zealand', 'da'),
('OMN', 'Oman', 'en'),
('OMN', 'Oman', 'de'),
('OMN', 'Oman', 'da'),
('PAK', 'Pakistan', 'en'),
('PAK', 'Pakistan', 'de'),
('PAK', 'Pakistan', 'da'),
('PAN', 'Panama', 'en'),
('PAN', 'Panama', 'de'),
('PAN', 'Panama', 'da'),
('PCN', 'Pitcairn', 'en'),
('PCN', 'Pitcairninseln', 'de'),
('PCN', 'Pitcairn', 'da'),
('PER', 'Peru', 'en'),
('PER', 'Peru', 'de'),
('PER', 'Peru', 'da'),
('PHL', 'Philippines', 'en'),
('PHL', 'Philippinen', 'de'),
('PHL', 'Filippinerne', 'da'),
('PLW', 'Palau', 'en'),
('PLW', 'Palau', 'de'),
('PLW', 'Palau', 'da'),
('PNG', 'Papua New Guinea', 'en'),
('PNG', 'Papua-Neuguinea', 'de'),
('PNG', 'Papua Ny Guinea', 'da'),
('POL', 'Poland', 'en'),
('POL', 'Polen', 'de'),
('POL', 'Polen', 'da'),
('PRI', 'Puerto Rico', 'en'),
('PRI', 'Puerto Rico', 'de'),
('PRI', 'Puerto Rico', 'da'),
('PRK', 'Korea, Democratic People''s Republic of', 'en'),
('PRK', 'Nordkorea', 'de'),
('PRK', 'Nordkorea', 'da'),
('PRT', 'Portugal', 'en'),
('PRT', 'Portugal', 'de'),
('PRT', 'Portugal', 'da'),
('PRY', 'Paraguay', 'en'),
('PRY', 'Paraguay', 'de'),
('PRY', 'Paraguay', 'da'),
('PSE', 'Palestine, State of', 'en'),
('PSE', 'Palästinensische Autonomiegebiete', 'de'),
('PSE', 'De palæstinensiske områder', 'da'),
('PYF', 'French Polynesia', 'en'),
('PYF', 'Französisch-Polynesien', 'de'),
('PYF', 'Fransk Polynesien', 'da'),
('QAT', 'Qatar', 'en'),
('QAT', 'Katar', 'de'),
('QAT', 'Qatar', 'da'),
('REU', 'Réunion', 'en'),
('REU', 'Réunion', 'de'),
('REU', 'Réunion', 'da'),
('ROU', 'Romania', 'en'),
('ROU', 'Rumänien', 'de'),
('ROU', 'Rumænien', 'da'),
('RUS', 'Russian Federation', 'en'),
('RUS', 'Russland', 'de'),
('RUS', 'Rusland', 'da'),
('RWA', 'Rwanda', 'en'),
('RWA', 'Ruanda', 'de'),
('RWA', 'Rwanda', 'da'),
('SAU', 'Saudi Arabia', 'en'),
('SAU', 'Saudi-Arabien', 'de'),
('SAU', 'Saudi-Arabien', 'da'),
('SDN', 'Sudan', 'en'),
('SDN', 'Sudan', 'de'),
('SDN', 'Sudan', 'da'),
('SEN', 'Senegal', 'en'),
('SEN', 'Senegal', 'de'),
('SEN', 'Senegal', 'da'),
('SGP', 'Singapore', 'en'),
('SGP', 'Singapur', 'de'),
('SGP', 'Singapore', 'da'),
('SGS', 'South Georgia and the South Sandwich Islands', 'en'),
('SGS', 'Südgeorgien und die Südlichen Sandwichinseln', 'de'),
('SGS', 'South Georgia og De Sydlige Sandwichøer', 'da'),
('SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'en'),
('SHN', 'St. Helena', 'de'),
('SHN', 'St. Helena', 'da'),
('SJM', 'Svalbard and Jan Mayen', 'en'),
('SJM', 'Spitzbergen und Jan Mayen', 'de'),
('SJM', 'Svalbard og Jan Mayen', 'da'),
('SLB', 'Solomon Islands', 'en'),
('SLB', 'Salomonen', 'de'),
('SLB', 'Salomonøerne', 'da'),
('SLE', 'Sierra Leone', 'en'),
('SLE', 'Sierra Leone', 'de'),
('SLE', 'Sierra Leone', 'da'),
('SLV', 'El Salvador', 'en'),
('SLV', 'El Salvador', 'de'),
('SLV', 'El Salvador', 'da'),
('SMR', 'San Marino', 'en'),
('SMR', 'San Marino', 'de'),
('SMR', 'San Marino', 'da'),
('SOM', 'Somalia', 'en'),
('SOM', 'Somalia', 'de'),
('SOM', 'Somalia', 'da'),
('SPM', 'Saint Pierre and Miquelon', 'en'),
('SPM', 'St. Pierre und Miquelon', 'de'),
('SPM', 'Saint Pierre og Miquelon', 'da'),
('SRB', 'Serbia', 'en'),
('SRB', 'Serbien', 'de'),
('SRB', 'Serbien', 'da'),
('SSD', 'South Sudan', 'en'),
('SSD', 'Südsudan', 'de'),
('SSD', 'Sydsudan', 'da'),
('STP', 'Sao Tome and Principe', 'en'),
('STP', 'São Tomé und Príncipe', 'de'),
('STP', 'São Tomé og Príncipe', 'da'),
('SUR', 'Suriname', 'en'),
('SUR', 'Suriname', 'de'),
('SUR', 'Surinam', 'da'),
('SVK', 'Slovakia', 'en'),
('SVK', 'Slowakei', 'de'),
('SVK', 'Slovakiet', 'da'),
('SVN', 'Slovenia', 'en'),
('SVN', 'Slowenien', 'de'),
('SVN', 'Slovenien', 'da'),
('SWE', 'Sweden', 'en'),
('SWE', 'Schweden', 'de'),
('SWE', 'Sverige', 'da'),
('SWZ', 'Eswatini', 'en'),
('SWZ', 'Eswatini', 'de'),
('SWZ', 'Eswatini', 'da'),
('SXM', 'Sint Maarten (Dutch part)', 'en'),
('SXM', 'Sint Maarten', 'de'),
('SXM', 'Sint Maarten', 'da'),
('SYC', 'Seychelles', 'en'),
('SYC', 'Seychellen', 'de'),
('SYC', 'Seychellerne', 'da'),
('SYR', 'Syrian Arab Republic', 'en'),
('SYR', 'Syrien', 'de'),
('SYR', 'Syrien', 'da'),
('TCA', 'Turks and Caicos Islands', 'en'),
('TCA', 'Turks- und Caicosinseln', 'de'),
('TCA', 'Turks- og Caicosøerne', 'da'),
('TCD', 'Chad', 'en'),
('TCD', 'Tschad', 'de'),
('TCD', 'Tchad', 'da'),
('TGO', 'Togo', 'en'),
('TGO', 'Togo', 'de'),
('TGO', 'Togo', 'da'),
('THA', 'Thailand', 'en'),
('THA', 'Thailand', 'de'),
('THA', 'Thailand', 'da'),
('TJK', 'Tajikistan', 'en'),
('TJK', 'Tadschikistan', 'de'),
('TJK', 'Tadsjikistan', 'da'),
('TKL', 'Tokelau', 'en'),
('TKL', 'Tokelau', 'de'),
('TKL', 'Tokelau', 'da'),
('TKM', 'Turkmenistan', 'en'),
('TKM', 'Turkmenistan', 'de'),
('TKM', 'Turkmenistan', 'da'),
('TLS', 'Timor-Leste', 'en'),
('TLS', 'Timor-Leste', 'de'),
('TLS', 'Timor-Leste', 'da'),
('TON', 'Tonga', 'en'),
('TON', 'Tonga', 'de'),
('TON', 'Tonga', 'da'),
('TTO', 'Trinidad and Tobago', 'en'),
('TTO', 'Trinidad und Tobago', 'de'),
('TTO', 'Trinidad og Tobago', 'da'),
('TUN', 'Tunisia', 'en'),
('TUN', 'Tunesien', 'de'),
('TUN', 'Tunesien', 'da'),
('TUR', 'Turkey', 'en'),
('TUR', 'Türkei', 'de'),
('TUR', 'Tyrkiet', 'da'),
('TUV', 'Tuvalu', 'en'),
('TUV', 'Tuvalu', 'de'),
('TUV', 'Tuvalu', 'da'),
('TWN', 'Taiwan, Province of China', 'en'),
('TWN', 'Taiwan', 'de'),
('TWN', 'Taiwan', 'da'),
('TZA', 'Tanzania, United Republic of', 'en'),
('TZA', 'Tansania', 'de'),
('TZA', 'Tanzania', 'da'),
('UGA', 'Uganda', 'en'),
('UGA', 'Uganda', 'de'),
('UGA', 'Uganda', 'da'),
('UKR', 'Ukraine', 'en'),
('UKR', 'Ukraine', 'de'),
('UKR', 'Ukraine', 'da'),
('UMI', 'United States Minor Outlying Islands', 'en'),
('UMI', 'Amerikanische Überseeinseln', 'de'),
('UMI', 'Amerikanske oversøiske øer', 'da'),
('URY', 'Uruguay', 'en'),
('URY', 'Uruguay', 'de'),
('URY', 'Uruguay', 'da'),
('USA', 'United States', 'en'),
('USA', 'Vereinigte Staaten', 'de'),
('USA', 'USA', 'da'),
('UZB', 'Uzbekistan', 'en'),
('UZB', 'Usbekistan', 'de'),
('UZB', 'Usbekistan', 'da'),
('VAT', 'Holy See (Vatican City State)', 'en'),
('VAT', 'Vatikanstadt', 'de'),
('VAT', 'Vatikanstaten', 'da'),
('VCT', 'Saint Vincent and the Grenadines', 'en'),
('VCT', 'St. Vincent und die Grenadinen', 'de'),
('VCT', 'Saint Vincent og Grenadinerne', 'da'),
('VEN', 'Venezuela, Bolivarian Republic of', 'en'),
('VEN', 'Venezuela', 'de'),
('VEN', 'Venezuela', 'da'),
('VGB', 'Virgin Islands, British', 'en'),
('VGB', 'Britische Jungferninseln', 'de'),
('VGB', 'De Britiske Jomfruøer', 'da'),
('VIR', 'Virgin Islands, U.S.', 'en'),
('VIR', 'Amerikanische Jungferninseln', 'de'),
('VIR', 'De Amerikanske Jomfruøer', 'da'),
('VNM', 'Viet Nam', 'en'),
('VNM', 'Vietnam', 'de'),
('VNM', 'Vietnam', 'da'),
('VUT', 'Vanuatu', 'en'),
('VUT', 'Vanuatu', 'de'),
('VUT', 'Vanuatu', 'da'),
('WLF', 'Wallis and Futuna', 'en'),
('WLF', 'Wallis und Futuna', 'de'),
('WLF', 'Wallis og Futuna', 'da'),
('WSM', 'Samoa', 'en'),
('WSM', 'Samoa', 'de'),
('WSM', 'Samoa', 'da'),
('YEM', 'Yemen', 'en'),
('YEM', 'Jemen', 'de'),
('YEM', 'Yemen', 'da'),
('ZAF', 'South Africa', 'en'),
('ZAF', 'Südafrika', 'de'),
('ZAF', 'Sydafrika', 'da'),
('ZMB', 'Zambia', 'en'),
('ZMB', 'Sambia', 'de'),
('ZMB', 'Zambia', 'da'),
('ZWE', 'Zimbabwe', 'en'),
('ZWE', 'Simbabwe', 'de'),
('ZWE', 'Zimbabwe', 'da');
