SELECT
    uuid::text,
    name,
    description,
    contact_email,
    contact_phone,
    web_link,
    street,
    house_number,
    address_addition,
    postal_code,
    city,
    country,
    holding_organization_id,
    legal_form,
    nonprofit,
    address_addition,
    state,
    ST_X(point) AS lon,
    ST_Y(point) AS lat,
    image_main_logo_uuid::text,
    image_light_mode_logo_uuid::text,
    image_dark_mode_logo_uuid::text
FROM {{schema}}.organization
WHERE uuid = $1