SELECT
    id,
    name,
    description,
    contact_email,
    contact_phone,
    website_link,
    street,
    house_number,
    address_addition,
    postal_code,
    city,
    country,
    holding_organization_id,
    legal_form,
    nonprofit,
    address_addition,
    state,
    ST_X(geo_pos) AS lon,
    ST_Y(geo_pos) AS lat,
    image_main_logo_id,
    image_light_mode_logo_id,
    image_dark_mode_logo_id
FROM {{schema}}.organization
WHERE id = $1