-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.accessibility_flag (
    flag integer NOT NULL,
    iso_639_1 character varying(2) NOT NULL,
    name text NOT NULL,
    topic_id integer NOT NULL,
    key text
);
