-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.contact_message (
    id bigint DEFAULT nextval('uranus.contact_message_id_seq'::regclass) PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    ip_hash character(64) NOT NULL,
    email text NOT NULL,
    message text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX contact_message_pkey ON uranus.contact_message(id int8_ops);
CREATE INDEX contact_message_created_at_idx ON uranus.contact_message(created_at timestamptz_ops);
CREATE INDEX contact_message_ip_created_at_idx ON uranus.contact_message(ip_hash bpchar_ops,created_at timestamptz_ops);
