-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.country (
    code character varying(3) NOT NULL,
    name text NOT NULL,
    iso_639_1 character varying(2) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX country_code_iso_unique ON uranus.country(code text_ops,iso_639_1 text_ops);
