-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.currency (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code character varying(3),
    iso_639_1 character varying(2),
    name text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX currency_pkey ON uranus.currency(id int4_ops);
