-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.display_preset (
    uuid uuid PRIMARY KEY,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    modified_at timestamp without time zone,
    org_uuid uuid NOT NULL,
    name text NOT NULL,
    description text,
    display_mode text,
    options jsonb,
    code text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX display_preset_pkey ON uranus.display_preset(uuid uuid_ops);
