-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_link (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    event_uuid uuid NOT NULL REFERENCES uranus.event(uuid) ON DELETE CASCADE,
    type text,
    label character varying(255),
    url text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_link_pkey ON uranus.event_link(id int4_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.event_link
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();
