-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_category (
    category_id integer,
    iso_639_1 character varying(2),
    name text NOT NULL,
    schema_org_type text
);

