-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_release_status_i18n (
    iso_639_1 character varying(2) NOT NULL,
    name text NOT NULL,
    key text,
    "order" integer,
    CONSTRAINT event_status_unique_key_lang UNIQUE (key, iso_639_1)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_status_unique_key_lang ON uranus.event_release_status_i18n(key text_ops,iso_639_1 text_ops);
