-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_occasion_type (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type_id integer NOT NULL,
    iso_639_1 character varying(2) NOT NULL,
    name text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_occasion_type_pkey ON uranus.event_occasion_type(id int4_ops);
