-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_date_projection (
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    release_status uranus.event_release_status NOT NULL DEFAULT 'inherited'::uranus.event_release_status,
    event_date_uuid uuid NOT NULL UNIQUE REFERENCES uranus.event_date(uuid) ON DELETE CASCADE,
    event_uuid uuid NOT NULL REFERENCES uranus.event(uuid) ON DELETE CASCADE,
    venue_uuid uuid,
    space_uuid uuid,
    venue_name text,
    venue_street text,
    venue_house_number text,
    venue_postal_code text,
    venue_city text,
    venue_country character(3),
    venue_state character varying(2),
    venue_point geometry(Point,4326),
    venue_link text,
    space_name character varying(255),
    space_description text,
    space_type text,
    space_total_capacity integer,
    space_seating_capacity integer,
    space_building_level integer,
    space_link text,
    space_accessibility_summary text,
    space_accessibility_flags bigint,
    start_date date NOT NULL,
    start_time time without time zone,
    end_date date,
    end_time time without time zone,
    entry_time time without time zone,
    duration integer,
    all_day boolean,
    ticket_link text,
    availability_status_id integer,
    accessibility_info text,
    custom text,
    event_start_at timestamp without time zone GENERATED ALWAYS AS (start_date + COALESCE(start_time, '00:00:00'::time without time zone)) STORED,
    event_end_at timestamp without time zone GENERATED ALWAYS AS (
        CASE
            WHEN end_date IS NULL THEN NULL::timestamp without time zone
            ELSE end_date + COALESCE(end_time, '23:59:00'::time without time zone)
        END) STORED,
    search_vector tsvector
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_date_projection_event_date_uuid_key ON uranus.event_date_projection(event_date_uuid uuid_ops);
CREATE INDEX idx_event_date_projection_venue_point ON uranus.event_date_projection USING GIST (venue_point gist_geometry_ops_2d);
CREATE INDEX idx_event_space_name_trgm ON uranus.event_date_projection USING GIN (space_name gin_trgm_ops);
CREATE INDEX idx_event_data_venue_name_trgm ON uranus.event_date_projection USING GIN (venue_name gin_trgm_ops);
CREATE INDEX idx_event_date_projection_search_vector ON uranus.event_date_projection USING GIN (search_vector tsvector_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.event_date_projection
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();
