-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_filter (
    uuid uuid PRIMARY KEY,
    params text,
    slug text,
    name text,
    description text,
    user_uuid uuid NOT NULL REFERENCES uranus."user"(uuid) ON DELETE CASCADE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_filter_pkey ON uranus.event_filter(uuid uuid_ops);
