-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event (
    uuid uuid PRIMARY KEY,
    external_id text,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    modified_at timestamp without time zone,
    release_date date,
    release_status uranus.event_release_status NOT NULL DEFAULT 'draft'::uranus.event_release_status,
    org_uuid uuid NOT NULL REFERENCES uranus.organization(uuid) ON DELETE CASCADE,
    venue_uuid uuid REFERENCES uranus.venue(uuid) ON DELETE SET NULL,
    space_uuid uuid REFERENCES uranus.space(uuid) ON DELETE SET NULL,
    content_iso_639_1 character varying(2),
    title text NOT NULL,
    description text,
    subtitle text,
    summary text,
    categories integer[],
    languages text[],
    tags text[],
    occasion_type_id integer,
    min_age integer,
    max_age integer,
    participation_info text,
    max_attendees integer,
    visitor_info_flags bigint,
    meeting_point text,
    source_link text,
    online_link text,
    ticket_link text,
    ticket_flags uranus.uranus_ticket_flag[] NOT NULL DEFAULT '{}'::uranus.uranus_ticket_flag[],
    price_type uranus.uranus_price_type NOT NULL DEFAULT 'not_specified'::uranus.uranus_price_type,
    currency character varying(8),
    min_price double precision,
    max_price double precision,
    custom text,
    style text,
    search_text text,
    registration_link text,
    registration_email text,
    registration_phone text,
    registration_deadline date,
    logo_mode integer NOT NULL DEFAULT 1
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_pkey ON uranus.event(uuid uuid_ops);
CREATE INDEX idx_event_release_status ON uranus.event(release_status enum_ops);
CREATE INDEX idx_event_venue_uuid ON uranus.event(venue_uuid uuid_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER trg_update_modified_at
    BEFORE UPDATE ON uranus.event
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

CREATE TRIGGER trg_update_search_text
    BEFORE INSERT OR UPDATE ON uranus.event
    FOR EACH ROW
    EXECUTE FUNCTION uranus.event_update_search_text();

