-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_type (
    type_id integer,
    iso_639_1 character varying(2),
    name text NOT NULL,
    schema_org_type text,
    CONSTRAINT event_type_pkey PRIMARY KEY (type_id, iso_639_1)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_type_pkey ON uranus.event_type(type_id int4_ops,iso_639_1 text_ops);
