-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_projection (
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    event_uuid uuid NOT NULL UNIQUE REFERENCES uranus.event(uuid) ON DELETE CASCADE,
    external_id text,
    release_status uranus.event_release_status NOT NULL DEFAULT 'draft'::uranus.event_release_status,
    org_uuid uuid NOT NULL,
    venue_uuid uuid,
    space_uuid uuid,
    title text NOT NULL,
    subtitle text,
    description text,
    summary text,
    org_name text,
    org_contact_email text,
    org_contact_phone text,
    org_link text,
    venue_name text,
    venue_street text,
    venue_house_number text,
    venue_postal_code text,
    venue_city text,
    venue_country character(3),
    venue_state character varying(2),
    venue_point geometry(Point,4326),
    venue_link text,
    space_type text,
    space_name character varying(255),
    space_description text,
    space_building_level integer,
    space_total_capacity integer,
    space_seating_capacity integer,
    space_link text,
    space_accessibility_flags bigint,
    space_accessibility_summary text,
    occasion_type_id integer,
    categories integer[],
    types jsonb,
    tags text[],
    languages text[],
    source_link text,
    online_link text,
    max_attendees integer,
    min_age integer,
    max_age integer,
    participation_info text,
    meeting_point text,
    currency character varying(8),
    min_price double precision,
    max_price double precision,
    image_alt_text text,
    image_license_id integer,
    image_creator_name text,
    image_copyright text,
    image_description text,
    ticket_flags uranus.uranus_ticket_flag[] NOT NULL DEFAULT '{}'::uranus.uranus_ticket_flag[],
    price_type uranus.uranus_price_type NOT NULL DEFAULT 'not_specified'::uranus.uranus_price_type,
    visitor_info_flags bigint,
    image_uuid uuid,
    search_text text,
    custom text,
    style text,
    ticket_link text,
    search_vector tsvector,
    image_ai_label text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_projection_event_uuid_key ON uranus.event_projection(event_uuid uuid_ops);
CREATE INDEX idx_event_title_trgm ON uranus.event_projection USING GIN (title gin_trgm_ops);
CREATE INDEX idx_event_description_trgm ON uranus.event_projection USING GIN (description gin_trgm_ops);
CREATE INDEX idx_event_subtitle_trgm ON uranus.event_projection USING GIN (subtitle gin_trgm_ops);
CREATE INDEX idx_event_org_name_trgm ON uranus.event_projection USING GIN (org_name gin_trgm_ops);
CREATE INDEX idx_event_venue_name_trgm ON uranus.event_projection USING GIN (venue_name gin_trgm_ops);
CREATE INDEX idx_event_projection_search_vector ON uranus.event_projection USING GIN (search_vector tsvector_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.event_projection
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();
