-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_type_link (
    event_uuid uuid NOT NULL REFERENCES uranus.event(uuid) ON DELETE CASCADE,
    type_id integer NOT NULL,
    genre_id integer NOT NULL DEFAULT 0,
    CONSTRAINT event_type_link_unique UNIQUE (event_uuid, type_id, genre_id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_type_link_unique ON uranus.event_type_link(event_uuid uuid_ops,type_id int4_ops,genre_id int4_ops);
