-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.event_date (
    uuid uuid PRIMARY KEY,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    modified_at timestamp without time zone,
    release_status uranus.event_release_status NOT NULL DEFAULT 'inherited'::uranus.event_release_status,
    event_uuid uuid REFERENCES uranus.event(uuid) ON DELETE CASCADE,
    venue_uuid uuid REFERENCES uranus.venue(uuid) ON DELETE SET NULL,
    space_uuid uuid REFERENCES uranus.space(uuid) ON DELETE SET NULL,
    start_date date NOT NULL,
    start_time time without time zone,
    end_date date,
    end_time time without time zone,
    entry_time time without time zone,
    duration integer,
    all_day boolean,
    ticket_link text,
    availability_status_id integer,
    accessibility_info text,
    sold_out boolean,
    limited_tickets_remaining boolean,
    custom text
);
COMMENT ON COLUMN uranus.event_date.venue_uuid IS 'Overrides the parent event''s venue. If NULL, the venue from uranus.event.venue_id is used.';

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX event_date_pkey ON uranus.event_date(uuid uuid_ops);
CREATE INDEX idx_event_date_event_uuid ON uranus.event_date(event_uuid uuid_ops);
CREATE INDEX idx_event_date_venue_uuid ON uranus.event_date(venue_uuid uuid_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER trg_update_modified_at
    BEFORE UPDATE ON uranus.event_date
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();
