-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.favorite_list (
    uuid uuid PRIMARY KEY,
    org_uuid uuid NOT NULL REFERENCES uranus.organization(uuid) ON DELETE CASCADE,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by uuid NOT NULL,
    modified_at timestamp without time zone,
    modified_by uuid,
    name text NOT NULL,
    description text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX favorite_list_pkey ON uranus.favorite_list(uuid uuid_ops);
