-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.favorite (
    list_uuid uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by uuid NOT NULL,
    context text NOT NULL,
    context_uuid uuid NOT NULL,
    CONSTRAINT favorite_unique_item UNIQUE (list_uuid, context, context_uuid)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX favorite_unique_item ON uranus.favorite(list_uuid uuid_ops,context text_ops,context_uuid uuid_ops);
