-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.genre_type (
    name text NOT NULL,
    genre_id integer NOT NULL,
    type_id integer,
    iso_639_1 character varying(2)
);

-- Indices -------------------------------------------------------

CREATE INDEX genre_type_type_id_idx ON uranus.genre_type(genre_id int4_ops);
