-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.geolist_country (
    code character(3),
    name text,
    slug text,
    state_label text
);

