-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.geolist_region (
    country_code character(3),
    state_code character varying(16),
    code text,
    name text,
    slug text,
    geometry geometry(Geometry,4326)
);

