-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.geolist_state (
    country_code character(3),
    code character varying(16),
    name text,
    slug text
);

