-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.image_type (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name character varying NOT NULL,
    description character varying,
    type_id integer NOT NULL,
    iso_639_1 character varying(2)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX image_type_pkey ON uranus.image_type(id int4_ops);
