-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.legal_form (
    key text PRIMARY KEY,
    schema_org text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX legal_form_pkey ON uranus.legal_form(key text_ops);
