-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.legal_form_i18n (
    key text REFERENCES uranus.legal_form(key) ON DELETE CASCADE,
    iso_639_1 character(2),
    name text NOT NULL,
    description text,
    CONSTRAINT legal_form_i18n_pkey PRIMARY KEY (key, iso_639_1)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX legal_form_i18n_pkey ON uranus.legal_form_i18n(key text_ops,iso_639_1 bpchar_ops);
