-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.license (
    key text PRIMARY KEY,
    spdx_id text,
    url text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX license_pkey ON uranus.license(key text_ops);
