-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.link_type (
    key text PRIMARY KEY
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX link_type_pkey ON uranus.link_type(key text_ops);
