-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.message (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    to_user_uuid integer NOT NULL,
    from_user_uuid integer NOT NULL,
    subject text NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX message_pkey ON uranus.message(id int4_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.message
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

