-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.organization_access_grants (
    src_org_uuid uuid REFERENCES uranus.organization(uuid) ON DELETE CASCADE REFERENCES uranus.organization(uuid) ON DELETE CASCADE,
    dst_org_uuid uuid REFERENCES uranus.organization(uuid) ON DELETE CASCADE REFERENCES uranus.organization(uuid) ON DELETE CASCADE,
    permissions bigint DEFAULT '0'::bigint,
    CONSTRAINT organization_access_grants_unique_pair UNIQUE (src_org_uuid, dst_org_uuid)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX organization_access_grants_unique_pair ON uranus.organization_access_grants(src_org_uuid uuid_ops,dst_org_uuid uuid_ops);
