-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.organization_member_link (
    org_uuid uuid NOT NULL REFERENCES uranus.organization(uuid) ON DELETE CASCADE,
    user_uuid uuid NOT NULL REFERENCES uranus."user"(uuid) ON DELETE CASCADE,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    invited_at timestamp without time zone DEFAULT now(),
    invited_by_user_uuid uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    accept_token text,
    has_joined boolean NOT NULL DEFAULT false,
    CONSTRAINT organization_member_unique UNIQUE (org_uuid, user_uuid)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX organization_member_unique ON uranus.organization_member_link(org_uuid uuid_ops,user_uuid uuid_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.organization_member_link
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

