-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.organization (
    uuid uuid PRIMARY KEY,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    modified_at timestamp without time zone,
    name text NOT NULL,
    description text,
    contact_email character varying(255),
    contact_phone character varying(50),
    web_link text,
    street character varying(255),
    house_number character varying(50),
    address_addition character varying,
    postal_code character varying(20),
    city character varying(100),
    country character varying(100),
    state character varying(2),
    holding_org_uuid uuid REFERENCES uranus.organization(uuid) ON DELETE SET NULL,
    legal_form text,
    nonprofit boolean,
    point geometry(Point,4326),
    api_import_token text,
    api_import_enabled boolean DEFAULT false,
    content_iso_639_1 character varying(2)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX organization_pkey ON uranus.organization(uuid uuid_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.organization
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

