-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.organization_partner_request (
    from_org_uuid uuid NOT NULL,
    to_org_uuid uuid NOT NULL,
    message text,
    from_user_uuid uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status text NOT NULL DEFAULT 'pending'::text,
    CONSTRAINT uq_org_partner_request UNIQUE (from_org_uuid, to_org_uuid)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX uq_org_partner_request ON uranus.organization_partner_request(from_org_uuid uuid_ops,to_org_uuid uuid_ops);
