-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.permission_bit (
    "group" text,
    name text,
    bit smallint NOT NULL,
    mask bigint NOT NULL
);

