-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.permission_label (
    "group" text,
    name text,
    iso_639_1 character(2),
    label text NOT NULL,
    description text NOT NULL
);

