-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.pluto_image (
    uuid uuid PRIMARY KEY,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    expiration_date date,
    file_name text NOT NULL,
    gen_file_name text,
    mime_type text,
    width integer,
    height integer,
    description text,
    alt_text text,
    exif jsonb,
    creator_name text,
    copyright text,
    license character varying(32),
    focus_x double precision,
    focus_y double precision,
    ai_label text CHECK (ai_label = ANY (ARRAY['none'::text, 'ai'::text, 'ai_generated'::text, 'ai_modified'::text]))
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX pluto_image_pkey ON uranus.pluto_image(uuid uuid_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.pluto_image
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

