-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.pluto_cache (
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    pluto_image_uuid uuid REFERENCES uranus.pluto_image(uuid) ON DELETE CASCADE,
    mime_type text,
    receipt text UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX pluto_cache_receipt_key ON uranus.pluto_cache(receipt text_ops);
