-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.pluto_context_rules (
    context text NOT NULL,
    identifier text NOT NULL,
    max_width integer,
    max_height integer,
    compression integer,
    max_file_size bigint
);

