-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.pluto_image_link (
    pluto_image_uuid uuid REFERENCES uranus.pluto_image(uuid) ON DELETE CASCADE,
    context text NOT NULL,
    context_uuid uuid NOT NULL,
    identifier text NOT NULL,
    CONSTRAINT image_context_identifier_unique UNIQUE (context, context_uuid, identifier)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX image_context_identifier_unique ON uranus.pluto_image_link(context text_ops,context_uuid uuid_ops,identifier text_ops);
