-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.portal_org_blocklist (
    uuid uuid PRIMARY KEY,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    modified_at timestamp without time zone,
    portal_uuid uuid NOT NULL,
    org_uuid uuid NOT NULL,
    reason text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX portal_org_blocklist_pkey ON uranus.portal_org_blocklist(uuid uuid_ops);
