-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.portal_temp (
    uuid uuid PRIMARY KEY,
    name text NOT NULL,
    description text,
    org_uuid uuid NOT NULL,
    spatial_filter_mode text,
    prefilter jsonb,
    wkb_geometry geometry,
    style jsonb,
    header jsonb,
    footer jsonb
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX portal_pkey ON uranus.portal_temp(uuid uuid_ops);
CREATE INDEX idx_portal_wkb_geometry ON uranus.portal_temp USING GIST (wkb_geometry gist_geometry_ops_2d);
