-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.portal2 (
    uuid uuid PRIMARY KEY,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    modified_at timestamp without time zone,
    org_uuid uuid NOT NULL,
    name text NOT NULL,
    description text,
    geometry_mode text,
    geometry geometry,
    filter jsonb,
    filter_type text NOT NULL DEFAULT 'geometry'::text CHECK (filter_type = ANY (ARRAY['geometry'::text, 'allowlist'::text, 'blocklist'::text, 'geometry_and_allowlist'::text, 'geometry_and_blocklist'::text])),
    slug text,
    config jsonb
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX portal2_pkey ON uranus.portal2(uuid uuid_ops);
CREATE INDEX portal2_org_uuid_idx ON uranus.portal2(org_uuid uuid_ops);
CREATE INDEX portal2_geometry_gist_idx ON uranus.portal2 USING GIST (geometry gist_geometry_ops_2d);
CREATE UNIQUE INDEX portal2_slug_unique ON uranus.portal2(slug text_ops) WHERE slug IS NOT NULL;
