-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.social_post_destination (
    uuid uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    social_post_uuid uuid NOT NULL REFERENCES uranus.social_post(uuid) ON DELETE CASCADE,
    destination text NOT NULL,
    status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text])),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    posted_at timestamp with time zone,
    error text,
    remote_id text,
    retry_count integer NOT NULL DEFAULT 0
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX social_post_destination_pkey ON uranus.social_post_destination(uuid uuid_ops);
