-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.social_post (
    uuid uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    context text NOT NULL,
    context_uuid text NOT NULL,
    context_identifier text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX social_post_pkey ON uranus.social_post(uuid uuid_ops);
