-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.space (
    uuid uuid PRIMARY KEY,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    venue_uuid uuid NOT NULL REFERENCES uranus.venue(uuid) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    web_link text,
    space_type text,
    building_level integer,
    area_sqm numeric(8,2),
    total_capacity integer,
    seating_capacity integer,
    accessibility_flags bigint,
    accessibility_summary text,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    modified_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    content_iso_639_1 character varying(2)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX space_pkey ON uranus.space(uuid uuid_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.space
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

