-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.space_feature (
    category text,
    key text UNIQUE,
    CONSTRAINT space_feature_pkey PRIMARY KEY (category, key)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX space_feature_feature_name_key ON uranus.space_feature(key text_ops);
CREATE UNIQUE INDEX space_feature_pkey ON uranus.space_feature(category text_ops,key text_ops);
