-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.space_feature_link (
    space_id integer,
    key text REFERENCES uranus.space_feature(key),
    CONSTRAINT space_feature_link_pkey PRIMARY KEY (space_id, key)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX space_feature_link_pkey ON uranus.space_feature_link(space_id int4_ops,key text_ops);
