-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.space_type (
    key text PRIMARY KEY,
    schema_org text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX space_type_pkey ON uranus.space_type(key text_ops);
