-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.state (
    code character varying(2) NOT NULL,
    country character varying(3) NOT NULL,
    name text NOT NULL
);

