-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.system_email_template (
    context text,
    iso_639_1 character varying(2),
    template text NOT NULL,
    subject text,
    CONSTRAINT system_email_template_pkey PRIMARY KEY (context, iso_639_1)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX system_email_template_pkey ON uranus.system_email_template(context text_ops,iso_639_1 text_ops);
