-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.team_member_role (
    type_id integer NOT NULL,
    name text NOT NULL,
    iso_639_1 character varying(2) NOT NULL,
    description text
);

