-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.todo (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    user_uuid uuid NOT NULL REFERENCES uranus."user"(uuid) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    due_date date,
    completed boolean NOT NULL DEFAULT false,
    importance text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX todo_pkey ON uranus.todo(id int4_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.todo
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

