-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.transport_station (
    uuid uuid PRIMARY KEY,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    name character varying(255) NOT NULL,
    city text,
    country character varying(3),
    point geometry(Point,4326),
    gtfs_station_code text UNIQUE,
    gtfs_location_type integer,
    gtfs_parent_station text,
    gtfs_wheelchair_boarding integer,
    gtfs_zone_id text,
    type character varying(20)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX transport_station_gtfs_station_code_key ON uranus.transport_station(gtfs_station_code text_ops);
CREATE UNIQUE INDEX transport_station_pkey ON uranus.transport_station(uuid uuid_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.transport_station
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

