-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.user_event_link (
    user_uuid uuid NOT NULL REFERENCES uranus."user"(uuid) ON DELETE CASCADE,
    event_uuid uuid NOT NULL REFERENCES uranus.event(uuid) ON DELETE CASCADE,
    permissions bigint NOT NULL DEFAULT '0'::bigint
);

