-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus."user" (
    uuid uuid PRIMARY KEY,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone,
    email character varying NOT NULL UNIQUE,
    password_hash text NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    username text UNIQUE,
    display_name character varying,
    first_name character varying,
    last_name character varying,
    locale character varying(2),
    theme character varying,
    activate_token text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_email_key ON uranus."user"(email text_ops);
CREATE UNIQUE INDEX user_pkey ON uranus."user"(uuid uuid_ops);
CREATE UNIQUE INDEX user_user_name_key ON uranus."user"(username text_ops);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus."user"
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

