-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.user_organization_link (
    user_uuid uuid NOT NULL REFERENCES uranus."user"(uuid) ON DELETE CASCADE,
    org_uuid uuid NOT NULL REFERENCES uranus.organization(uuid) ON DELETE CASCADE,
    permissions bigint NOT NULL DEFAULT '0'::bigint
);

-- Indices -------------------------------------------------------

CREATE INDEX user_organization_link_org_uuid_user_uuid_idx ON uranus.user_organization_link(org_uuid uuid_ops,user_uuid uuid_ops);
