-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.venue (
    uuid uuid PRIMARY KEY,
    created_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by uuid REFERENCES uranus."user"(uuid) ON DELETE SET NULL,
    modified_at timestamp without time zone,
    org_uuid uuid NOT NULL REFERENCES uranus.organization(uuid) ON DELETE CASCADE,
    type text,
    name character varying(255) NOT NULL,
    description text,
    summary text,
    contact_email character varying,
    contact_phone character varying,
    web_link text,
    street character varying(255),
    house_number character varying(50),
    postal_code character varying(20),
    city character varying(100),
    country character(3) CHECK (char_length(country::text) = 3),
    state character varying(2),
    point geometry(Point,4326),
    opened_at date,
    closed_at date,
    ticket_info text,
    ticket_link text,
    opening_hours text,
    accessibility_flags bigint,
    accessibility_summary text,
    content_iso_639_1 character varying(2),
    slug text CHECK (slug IS NULL OR slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text),
    scope text NOT NULL DEFAULT 'standard'::text CHECK (scope = ANY (ARRAY['organization'::text, 'shared'::text])),
    osm_id bigint,
    building geometry(Geometry,4326),
    wikidata text,
    wikipedia text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX venue_pkey ON uranus.venue(uuid uuid_ops);
CREATE INDEX idx_venue_point ON uranus.venue USING GIST (point gist_geometry_ops_2d);

-- Triggers -------------------------------------------------------

CREATE TRIGGER set_modified_at
    BEFORE UPDATE ON uranus.venue
    FOR EACH ROW
    EXECUTE FUNCTION uranus.update_modified_at();

