-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.venue_type (
    key text PRIMARY KEY,
    schema_org text NOT NULL,
    marker_style text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX venue_type_pkey1 ON uranus.venue_type(key text_ops);
