-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.venue_type_i18n (
    key text,
    iso_639_1 character(2),
    name text NOT NULL,
    description text,
    CONSTRAINT venue_type_pkey PRIMARY KEY (key, iso_639_1)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX venue_type_pkey ON uranus.venue_type_i18n(key text_ops,iso_639_1 bpchar_ops);
