-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.visitor_information_flag (
    flag integer,
    iso_639_1 character varying(2),
    name character varying(255),
    topic_id integer,
    key text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX visitor_information_flag_flag_lang_topic_idx ON uranus.visitor_information_flag(flag int4_ops,iso_639_1 text_ops,topic_id int4_ops);
