-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.visitor_information_topic (
    topic_id integer NOT NULL,
    iso_639_1 character varying(2),
    name text,
    key text
);

