-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE uranus.wkb_polygon (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    context text NOT NULL,
    context_id integer NOT NULL,
    geometry geometry(Polygon,4326),
    name text,
    description text,
    key text UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX wkb_poly_key_key ON uranus.wkb_polygon(key text_ops);
CREATE UNIQUE INDEX wkb_poly_pkey ON uranus.wkb_polygon(id int4_ops);
